In [1]:
%pip install torch

Note: you may need to restart the kernel to use updated packages.


In [2]:
import torch, torchvision
print(torch.__version__, torchvision.__version__)

2.9.0+cpu 0.24.0+cpu


In [3]:
from torchvision import models

In [4]:
dir(models)

['AlexNet',
 'AlexNet_Weights',
 'ConvNeXt',
 'ConvNeXt_Base_Weights',
 'ConvNeXt_Large_Weights',
 'ConvNeXt_Small_Weights',
 'ConvNeXt_Tiny_Weights',
 'DenseNet',
 'DenseNet121_Weights',
 'DenseNet161_Weights',
 'DenseNet169_Weights',
 'DenseNet201_Weights',
 'EfficientNet',
 'EfficientNet_B0_Weights',
 'EfficientNet_B1_Weights',
 'EfficientNet_B2_Weights',
 'EfficientNet_B3_Weights',
 'EfficientNet_B4_Weights',
 'EfficientNet_B5_Weights',
 'EfficientNet_B6_Weights',
 'EfficientNet_B7_Weights',
 'EfficientNet_V2_L_Weights',
 'EfficientNet_V2_M_Weights',
 'EfficientNet_V2_S_Weights',
 'GoogLeNet',
 'GoogLeNetOutputs',
 'GoogLeNet_Weights',
 'Inception3',
 'InceptionOutputs',
 'Inception_V3_Weights',
 'MNASNet',
 'MNASNet0_5_Weights',
 'MNASNet0_75_Weights',
 'MNASNet1_0_Weights',
 'MNASNet1_3_Weights',
 'MaxVit',
 'MaxVit_T_Weights',
 'MobileNetV2',
 'MobileNetV3',
 'MobileNet_V2_Weights',
 'MobileNet_V3_Large_Weights',
 'MobileNet_V3_Small_Weights',
 'RegNet',
 'RegNet_X_16GF_Weights'

In [5]:
alexnet = models.AlexNet()
print(alexnet)

AlexNet(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (3): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (4): ReLU(inplace=True)
    (5): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (6): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (7): ReLU(inplace=True)
    (8): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (9): ReLU(inplace=True)
    (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (avgpool): AdaptiveAvgPool2d(output_size=(6, 6))
  (classifier): Sequential(
    (0): Dropout(p=0.5, inplace=False)
    (1): Linear(in_features=9216, out_features=4096, bias=True)
 

In [6]:
# 활성화 함수
# Relu

In [7]:
# ResNet-101
# 스킵커넥션 (Skip Connection , Residual Block)
# W , x 학습 대신에 f(x) 잔차(residual)(입력 x와의 차이)만 학습
# 초기x의 값이 지름길을 통해 뒤쪽 레이어까지 직접 전달... 층이 깊을수록 기울기가 소실 되는 문제
# 보통 레이어가 100층을 넘어가면 기울기가 소실되거나 폭발하는 현상이 필연적임. -> 이걸 해결해서 더 깊은 층을 볼 수 있게 됨
# H(x) = F(x) + x
resnet = models.resnet101(pretrained = False)
resnet

d:\pandas_main\.venv\Lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
d:\pandas_main\.venv\Lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)


ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [8]:
from PIL import Image
# img = Image.open('')

In [9]:
# alexnet.eval() 모델을 평가할때 평가모드로 전환
# 모델 내의 배치를 정규화하고 층, 드랍아웃층이 평가모드로 작동
# 배치정규화 : 학습에는 현재 배치의 평균과 분산 사용 평가모드가 되면 학습 과정에 전체에서 누적된 평균 / 분산
# 드랍아웃 : 학습시에는 랜덤하게 뉴런을 끄지만 , 평가모드로 전환되면 모든 뉴런을 사용
# alexnet(x_test) : 예측하는것. 

In [10]:
# 합성곱 연산 -> 이미지의 특징을 추출
# convolution(합성곱) - CNN
# 28(높이) 28(너비) 39(깊이)  ->  3차원 tensor 
# 일반적으로 커널은 3 x 3 or 5 x 5 많이 사용함
# 5 X 5 이미지가 있고 커널이 3 x 3일때 하나씩 출력하는 것. 2를 뺴면 됌ㅋ
# 패딩을 주면 원본크가가 유지가 됨 / 패딩을 주지 않으면 이미지가 줄어듬.
# 


In [11]:
import torch
import torch.nn as nn # 신경망을 구성하는 역할 : nn

# CNN을 구할때 배치크기 x 채널크기 x 높이 x 너비
# torch는 채널이 앞에 있음 (tensorflow는 채널이 뒤에 있음 )

inputs = torch.Tensor(1,1,28,28) # 채널 1개 28x28 크기를 갖는 1개의 흑백이미지 
print(f'텐서의 크기 : {inputs.size()}')

텐서의 크기 : torch.Size([1, 1, 28, 28])


In [12]:
# 합성곱 층과 폴링
conv1 = nn.Conv2d(1,32,3,padding=1) # 차례대로 채널 , 입력 , 커널사이즈 / 얘가 출력하는 것은 특성맵임. strid=1 padding=1  28,28,32
print(conv1)


Conv2d(1, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))


In [13]:
# 2번째 합성곱 층
conv2 = nn.Conv2d(32,64,3,padding=1)
print(conv2)

Conv2d(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))


In [14]:
pool = nn.MaxPool2d(2) #2x2
print(pool)

MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)


In [15]:
# 데이터 통과하기
inputs.size() # 샘플1개 , 채널1개 , 28사이즈
out = conv1(inputs)
out.size()

torch.Size([1, 32, 28, 28])

In [16]:
out = pool(out) # pool은 2바이2
print(out.size())

torch.Size([1, 32, 14, 14])


In [17]:
out = conv2(out)
print(out.size())

torch.Size([1, 64, 14, 14])


In [18]:
out = pool(out)
print(out.size())

torch.Size([1, 64, 7, 7])


In [19]:
out.size(0) # 0번째 차원 숫자에 따라 차원이 출력됨

1

In [20]:
out.view(out.size(0),-1)

tensor([[ 8.9279e+30,  1.6430e-01,  1.6430e-01,  ..., -9.8610e-03,
         -9.8610e-03, -9.8610e-03]], grad_fn=<ViewBackward0>)

In [21]:
out = out.view(out.size(0),-1)
print(out.size())

torch.Size([1, 3136])


In [22]:
fc = nn.Linear(3136,10)
out = fc(out)
print(out.size())

torch.Size([1, 10])


In [23]:
import torch.optim as optim
import torch.nn.functional as F
import torchvision
from torchvision import transforms
from torch.utils.data import DataLoader



In [24]:
# C , H , W

transform = transforms.Compose( [transforms.ToTensor(), transforms.Normalize((0.5 , ) , (0.5 , ))] )
# 모든데이터에 평균이 0.5 표준편차가 0.5 되게 설정
train_dataset = torchvision.datasets.FashionMNIST(root='./data' , train = True , download=True , transform=transform)
test_dataset = torchvision.datasets.FashionMNIST(root='./data' , train = False , download=True , transform=transform)

train_load = DataLoader(train_dataset , batch_size=64 , shuffle=True)
test_load = DataLoader(test_dataset , batch_size=64 , shuffle=False)

In [25]:
import numpy as np
# 채널 정보 확인
for data in train_dataset:
    print(data[0].size())
    break

torch.Size([1, 28, 28])


In [26]:
#loader에 있는 정보 보기 -> 64개 데이터의 1, 28,28
for data in train_load:
    print(data[0].size())
    break

torch.Size([64, 1, 28, 28])


In [27]:
class CNN(nn.Module):
    def __init__(self):
        super(CNN , self).__init__()  # 64 1 28 28
        self.conv1 = nn.Conv2d(1,32,3,padding=1)
        self.conv2 = nn.Conv2d(32,64,3,padding=1)
        self.pool = nn.MaxPool2d(2)
        self.fc1 = nn.Linear( 64*7*7 ,128 )
        self.fc2 = nn.Linear(128 , 10) #은닉층
    def forward(self ,  x):
        x = self.pool(F.relu(self.conv1(x))) # (64 1 28 28) 패딩을 줬기때문에 값 그대로  -> (64 32 14 14)
        x = self.pool(F.relu(self.conv2(x))) # (64 32 14 14)  -> (64 64 7 7)
        x = x.view(x.size(0) , -1)
        x = F.relu(self.fc1(x)) # Error : 64x1568 and 3136x128
        out = self.fc2(x)
        return out

model = CNN()
model

device = torch.device('cuda'  if torch.cuda.is_available() else 'cpu')
model.to(device)

criterion = nn.CrossEntropyLoss() #손실함수 설정해줘야함 /  손실함수는 내부에 소프트맥스 + 로그 손실 계산함 ( 다중 클래스 )
optimizer = optim.Adam(model.parameters() , lr = 0.001)




In [28]:
len(train_load) #데이터 개수

938

In [29]:
# 훈련 루프
from tqdm import tqdm

num_epochs = 5
for epoch in range(num_epochs):
    model.train() # dropout이나 배치nomal 기능성 레이어(층)을 활성화 시킴
    # 손실률은 계속 계산해야하기떄문에 하기 코드작성
    runing_loss = 0.0
    for inputs , labels in train_load:
        inputs , labels = inputs.to(device) , labels.to(device)    
        optimizer.zero_grad() # 그레디언트 초기화
        outputs = model(inputs) #forward 호출하여 예측한다.
        loss = criterion(outputs , labels) # 손실계산
        loss.backward() #역전파(그레이던트(기울기) 계산 -> 자동미분)
        optimizer.step() # 역전파가 적용 / 위로 타고 올라가면서 파라메터(가중치)를 업데이트시켜줌
        runing_loss += loss.item()
    print(f'Epoch : {epoch+1} / {num_epochs} , loss : {runing_loss / len(train_load):.4f}')



Epoch : 1 / 5 , loss : 0.4355
Epoch : 2 / 5 , loss : 0.2813
Epoch : 3 / 5 , loss : 0.2354
Epoch : 4 / 5 , loss : 0.2049
Epoch : 5 / 5 , loss : 0.1787


In [30]:
# 평가모드로 변환 정규화하는애들은 학습할떄 전체 데이터로 하기위해
model.eval() #평가모드
correct = 0
total = 0
with torch.no_grad():
    for inputs , labels in test_load:
        inputs , labels = inputs.to(device) , labels.to(device)
        output = model(inputs)
        _, predicted = torch.max(output.data , 1) # 최대 확률 클래스 예측
        total += labels.size(0)
        correct += (predicted == labels).sum().item()
    print(f'test accuracy : {correct / total}')


test accuracy : 0.9099


In [31]:
test_data = next(iter(test_load))[0].size()
# torch.max(model(test_data))

In [32]:
X , y = next(iter(test_load))
_, predicted = torch.max(model(X),1)
predicted[:5] , y[:5] , predicted[-5:] , y[-5:]

(tensor([9, 2, 1, 1, 6]),
 tensor([9, 2, 1, 1, 6]),
 tensor([0, 7, 7, 8, 5]),
 tensor([0, 7, 7, 8, 5]))

### 3차원 컬러 이미지

#### RGB 체널의 각각의 평균과 표준편차

In [33]:
transform = transforms.Compose( [transforms.ToTensor()] )

test = torchvision.datasets.CIFAR10(root='./data' , train = True ,
                                             download=True , transform=transform)


mean = torch.zeros(3)
std = torch.zeros(3)
for data , _ in test:
    mean += data.mean(dim=(1,2))
    std += data.std(dim=(1,2))
    # print(data[0].size())
    # print(data[0].mean())# tensor의 평균
    # print(data[0].mean(dim=(1,2))) # RGB 평균
    # print(data[0])
print(mean / len(test))
print(std / len(test))

tensor([0.4914, 0.4822, 0.4465])
tensor([0.2023, 0.1994, 0.2010])


In [34]:
(mean / len(test)).cpu().numpy()

array([0.4914008 , 0.482159  , 0.44653094], dtype=float32)

#### 학습 / 검증 / 테스트 데이터 로더

In [35]:

rgb_mean = mean / len(test)
rgb_std = std / len(test)
transform = transforms.Compose( [transforms.ToTensor(),
                                 transforms.Normalize(rgb_mean , rgb_std)] )

full_train_dataset = torchvision.datasets.CIFAR10(root='./data' , train = True ,
                                             download=True , transform=transform)
test_dataset = torchvision.datasets.CIFAR10(root='./data' , train = False ,
                                            download=True , transform=transform)

from torch.utils.data import random_split
# train/val 분할 : 8:2
train_size = int(len(full_train_dataset)*0.8)
val_size = len(full_train_dataset) - train_size
train_dataset , val_dataset = random_split(full_train_dataset , [train_size , val_size])



train_load = DataLoader(train_dataset , batch_size=64 , shuffle=True)
val_load = DataLoader(val_dataset , batch_size=64 , shuffle=False)
test_load = DataLoader(test_dataset , batch_size=64 , shuffle=False)

In [36]:
next(iter(train_dataset))[0].size(0)

3

In [37]:
for data in train_load:
    print(data[0].size())
    break

torch.Size([64, 3, 32, 32])


In [38]:
data[0].size()

torch.Size([64, 3, 32, 32])

#### 컬러이미지 처리 CNN 모델을 구현
- 손실함수
- 옵티마이져
- 스케줄러

In [39]:
# 모델클래스
# 손실함수
# 역전파를 위한 optimizer
# 학습루프
# 평가
# 예측

In [40]:
class CNN_CIFAR10(nn.Module):
    def __init__(self):
        super(CNN , self).__init__()  # 64, 3, 32, 32
        self.conv1 = nn.Conv2d(3,32,3,padding=1)
        self.conv2 = nn.Conv2d(32,64,3,padding=1)
        self.pool = nn.MaxPool2d(2)
        self.fc1 = nn.Linear( 64*8*8 ,128 )
        self.fc2 = nn.Linear(128 , 10) #은닉층
    def forward(self ,  x):
        x = self.pool(F.relu(self.conv1(x))) # (64, 3, 32, 32)  ->  (64, 32, 16, 16)
        x = self.pool(F.relu(self.conv2(x))) # (64, 32, 16, 16) -> (64, 64, 8, 8)
        x = x.view(x.size(0) , -1)
        x = F.relu(self.fc1(x)) 
        out = self.fc2(x)
        return out

model = CNN()
model

cnn_cifar10_model = CNN_CIFAR10()
device = torch.device('cuda'  if torch.cuda.is_available() else 'cpu')
model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(cnn_cifar10_model.parameters() , lr = 0.001)
scheduler = optim.lr_scheduler.StepLR(optimizer , step_size=7 , gamma=0.1) #gamma : 매번 학습할떄마다(7epoch) lr*0.1



TypeError: super(type, obj): obj (instance of CNN_CIFAR10) is not an instance or subtype of type (CNN).

#### EarlyStopping 

In [ ]:
class EarlyStopping:
    def __init__(self , patience = 5 , min_delta = 0):
        self.patience = patience
        self.min_delta = min_delta
        self.count = 0
        self.best_loss = float('inf')
    def __call__(self , val_loss):
        if val_loss < self.best_loss - self.min_delta:
            self.best_loss = val_loss
            self.counter = 0
        else:
            self.counter += 1
            if self.counter >= self.patience:
                return True # 조기 종류
        return False
early_stopping = EarlyStopping()


#### 훈련 / 검증 함수 (accuracy 포함)

In [ ]:
def train_epoch(model, loader , criterion , optimizer , device):
    model.train() # dropout이나 배치nomal 기능성 레이어(층)을 활성화 시킴
    # 손실률은 계속 계산해야하기떄문에 하기 코드작성
    runing_loss = 0.0
    correct = 0
    total = 0
    iterator = tqdm(enumerate(loader),total = len(loader) , desc='Train')
    for batch_idx , (inputs , labels) in iterator:
        inputs , labels = inputs.to(device) , labels.to(device)    
        optimizer.zero_grad() # 그레디언트 초기화
        outputs = model(inputs) # 순전파 forward 호출 --> 예측
        loss = criterion(outputs , labels) # 손실계산
        loss.backward() #역전파(그레이던트(기울기) 계산 -> 자동미분)
        optimizer.step() # 역전파가 적용 / 위로 타고 올라가면서 파라메터(가중치)를 업데이트시켜줌
        runing_loss += loss.item()

        _ , predicted = torch.max(outputs.data,1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()  #CPU로 계싼그래프에서 빠짐. (device GPU에서 함)
        iterator.set_postfix({'loss' : f'{loss.item():.3f}' , 'acc': f'{correct/total:.3f}'})
    avg_loss = runing_loss / len(loader)
    accuracy = correct / total
    return avg_loss , accuracy

#### 훈련루프

In [ ]:
# 훈련 루프
num_epochs = 20
best_val_loss = float('inf')
for epoch in range(num_epochs):
    train_loss, train_acc =  train_epoch(cnn_cifar10_model,train_load,criterion,optimizer,device)
    scheduler.step() # 스케줄러 업데이트
    
    # early stoppin check
    if early_stopping(best_val_loss):
        print(f'Early Stopping epoch : {epoch+1}')
        break

In [ ]:
float('inf')

inf

In [ ]:
0.1 < float('inf')