In [ ]:
# Tensor (다차원배열)
# 데이터를 저장하는 다차원 배열 또는 컨테이너 배열
# 딥러닝이 학습할때 사용하는 자료구조
# 0차원 Tensor (스칼라) : 0이나 1처럼 단일 데이터를 뜻함.
# 1차원 Tensor (백터) : 리스트 형태로 [1,2,3,4] 로 보면 됌
# 2차원 Tensor (행렬) : 행과 열로 이루어진 데이터로 표데이터 , 흑백이미지 (가로픽셀 x 세로픽셀)
# 3차원 Tensor (컬러이미지) : 흑백이미지 + 채널정보(R G B)
# 고차원 Tensor (동영상) : 이미지개수 x 가로픽셀 x 세로픽셀 x 채널정보(R G B)
# 데이터의 표준형식 : 일관된 숫자 형식
# 효율적인 계산 : GPU를 지원하기때문에 병렬 계산에 유리함.
# 딥러닝 프레임워크 : 텐서플로 , 파이토치(페이스북에서 개발한 머신러닝라이브러리/동적)




In [ ]:
%pip install torch torchvision  # 파이토치 설치  /  torchvision <- deeplearning 에 사용됨

  Using cached torch-2.9.0-cp313-cp313-win_amd64.whl.metadata (30 kB)
  Using cached torchvision-0.24.0-cp313-cp313-win_amd64.whl.metadata (5.9 kB)
  Using cached fsspec-2025.9.0-py3-none-any.whl.metadata (10 kB)
Using cached torch-2.9.0-cp313-cp313-win_amd64.whl (109.3 MB)
Using cached torchvision-0.24.0-cp313-cp313-win_amd64.whl (4.3 MB)
Using cached fsspec-2025.9.0-py3-none-any.whl (199 kB)

   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ---------------------------------------- 0/3 [fsspec]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- -------------------------- 1/3 [torch]
   ------------- ------------------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [3]:
# 기본연산
#  파이토치는 numpy의 array와 유사함.
import torch

# 빈 Tensor 생성
x = torch.empty(3,4)
print(x)




tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [ ]:
# 랜덤 Tensor
# empty나 rand가 비슷함 
x = torch.rand(3,4)
x


tensor([[0.9892, 0.2093, 0.6946, 0.6795],
        [0.7995, 0.6019, 0.2199, 0.2067],
        [0.5100, 0.3235, 0.1675, 0.7774]])

In [5]:
# 0으로 Tensor 초기화
torch.zeros(3,4,dtype=torch.long) # 데이터타입을 세밍하게 지정해주는 경우가 좋음

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [6]:
# 1로 Tensor 초기화
torch.ones(3,4,dtype=torch.long)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [7]:
[3.5,3,2.1]

[3.5, 3, 2.1]

In [9]:
torch.tensor([3.5,3,2.1])

tensor([3.5000, 3.0000, 2.1000])

In [10]:
import numpy as np

print( torch.tensor([3.5,3,2.1]) )
print( np.array( [3.5,3,2.1] ) )



tensor([3.5000, 3.0000, 2.1000])
[3.5 3.  2.1]


In [11]:
# 기존의 Tensor를 기번으로 새로운 Tensor 생성 가능 (복사하는 기능이 있음)

x = torch.ones(3,4)
y = torch.rand_like( x,dtype=torch.float)
x , y



(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[0.2146, 0.5719, 0.9002, 0.9201],
         [0.2142, 0.2211, 0.8783, 0.1829],
         [0.6651, 0.5096, 0.0063, 0.0216]]))

In [ ]:
# Tensor 연산해보자

import torch

x = torch.rand(3,4)
y = torch.rand(3,4)

x,y,x+y


(tensor([[0.4693, 0.1617, 0.9426, 0.7226],
         [0.8220, 0.0655, 0.4329, 0.9880],
         [0.2302, 0.9869, 0.6609, 0.6436]]),
 tensor([[0.1655, 0.1412, 0.0971, 0.2987],
         [0.1540, 0.3969, 0.1952, 0.3999],
         [0.8497, 0.3598, 0.8874, 0.3569]]),
 tensor([[0.6348, 0.3028, 1.0398, 1.0213],
         [0.9759, 0.4624, 0.6281, 1.3879],
         [1.0799, 1.3466, 1.5483, 1.0006]]))

In [ ]:
torch.add(x,y) # 이렇게 덧셈해도 됌

tensor([[0.6348, 0.3028, 1.0398, 1.0213],
        [0.9759, 0.4624, 0.6281, 1.3879],
        [1.0799, 1.3466, 1.5483, 1.0006]])

In [ ]:
# in-place : 판다스에서는 in-place를 사용하면 자기 자신을 바꿔주지만 
# Tensor에서는 메서드 이름 뒤에 _(언더스코어)를 붙여서 사용함.

y.add_(x) # y = y + x (y 자체를 변경!)

tensor([[0.6348, 0.3028, 1.0398, 1.0213],
        [0.9759, 0.4624, 0.6281, 1.3879],
        [1.0799, 1.3466, 1.5483, 1.0006]])

In [ ]:
# 1차원 곱셈은 이렇게 진행됨
x = torch.tensor( [1,2,3] )
y = torch.tensor( [1,2,3] )

x*y



tensor([1, 4, 9])

In [ ]:
# 행렬 곱셈
# 양쪽의 행렬 중 첫번째 행렬에서 열과 두번째 행렬에서 행의 숫자가 동일해야 연산이 가능 
# 행렬의 곱셈 후 표시는 첫번째 행 , 두번째 열로 표시됨


x = torch.rand(3,4)
y = torch.rand(4,5)

x,y,torch.mm(x,y) , x@y # torch.mm(x,y) 출력 값이 python 3.5버전부터 x@y로도 동일한 값이 나옴.

(tensor([[0.4781, 0.5668, 0.9249, 0.1812],
         [0.3692, 0.8060, 0.0409, 0.4769],
         [0.6761, 0.1596, 0.4259, 0.7189]]),
 tensor([[0.6807, 0.6069, 0.7694, 0.1838, 0.1722],
         [0.9822, 0.0623, 0.2868, 0.1571, 0.5582],
         [0.0881, 0.8583, 0.4352, 0.1100, 0.6312],
         [0.5588, 0.6212, 0.7658, 0.0089, 0.3921]]),
 tensor([[1.0649, 1.2319, 1.0717, 0.2803, 1.0535],
         [1.3131, 0.6057, 0.8983, 0.2032, 0.7262],
         [1.0562, 1.2324, 1.3019, 0.2026, 0.7562]]),
 tensor([[1.0649, 1.2319, 1.0717, 0.2803, 1.0535],
         [1.3131, 0.6057, 0.8983, 0.2032, 0.7262],
         [1.0562, 1.2324, 1.3019, 0.2026, 0.7562]]))

In [22]:
# 슬라이싱 가능

x = torch.rand(4,5)
x[0,2:]



tensor([0.9821, 0.7042, 0.8858])

In [26]:
# 행렬의 특정요소를 찾는법

x[1,1], x[1,1].item() #item()을 쓰면 데이터타입이 다르게 출력됨


(tensor(0.4377), 0.4376525282859802)

In [ ]:
# GPU에서 돌아가는 구조.
# 
type(x[1,1]) , type(x[1,1].item())

(torch.Tensor, float)

In [ ]:
# Tensor 크기 변경
# numpy 동일한 기능 reshape

x = torch.rand(4,4)
y = x.view(16)  # view(-1) 여기서 -1 은 자동 계산
x,y,x.shape,y.shape

(tensor([[0.5491, 0.2102, 0.1555, 0.7151],
         [0.9916, 0.9246, 0.8223, 0.7142],
         [0.7903, 0.0236, 0.8948, 0.0021],
         [0.5287, 0.5571, 0.5725, 0.4135]]),
 tensor([0.5491, 0.2102, 0.1555, 0.7151, 0.9916, 0.9246, 0.8223, 0.7142, 0.7903,
         0.0236, 0.8948, 0.0021, 0.5287, 0.5571, 0.5725, 0.4135]),
 torch.Size([4, 4]),
 torch.Size([16]))

In [29]:
# x 는 4행 4열
x.view(2,8) # 2밖에 올 수 없으니 자동계산인 -1을 넣어도 됌
x.view(-1,8) # 확실히 값을 아는 경우에만 자동 계산인 -1을 넣어줘야함
x.size() # shape랑 똑같은 기능.

# view는 reshpe와 동일함. tensor 모양 변경
# size는 shape와 동일함. tnesor 모양 확인
# 가독성 view size가 사용되었다는 것은 해당 자료구조가 tensor라는것을 명시

torch.Size([4, 4])

In [ ]:
# tensor -> numpy 바꾸기

import torch
import numpy as np

a = torch.ones(5)
# np.array(a)
a.numpy()  # tensor 자체에 numpy를 해주는것.

array([1., 1., 1., 1., 1.], dtype=float32)

In [33]:
# numpy -> tensor 바꾸기

a = np.array( [1,2,3,4,5] )
torch.from_numpy(a) # torch에 numpy를 하면 tensor로 바뀜

tensor([1, 2, 3, 4, 5])

In [36]:
# GPU 사용 -> cuda를 쓰면 GPU를 쓰겠단거임.
torch.cuda.is_available()


False

In [ ]:
if torch.cuda.is_available():
    device = torch.device('cuda') # GPU (병렬로 연산)
    #tensor들은 GPU에서 연산해야되기때문에 생성을 GPU에서 생성
    x = torch.ones(5,device=device) #GPU에서 생성
    y = torch.ones(5) # CPU 에서 생성
    y = y.to(device) # CPU -> GPU로 이동 / to('소문자)
    z = x + y
    print(f'GPU 연산결과 : {z}')
    print(f'다시 CPU로 : {z.to("cpu",torch.double)}')
else:
    print('cuda를 사용할 수 없다')
    device = torch.device('CPU')

# 코랩에서 확인 가능
# torch.cuda.is_available() <- 코랩에서는 True로 나옴.


cuda를 사용할 수 없다


In [38]:

# 행열의 곱
# ( x,y )  *  ( x1,y1 )
# # y , x1 의 차수는 같아야함.
# 행열곱의 결과의 최종은 x , y1 

# Tensor는 딥러닝을 위해 만들 저료구조
# 내부에 GPU 연산에 특화된 구조임.
# 일반적인 모양은 numpy와 동일함.

# Tensor는 GPU 연산을 지원함.


In [ ]:
# Tensor에는 자동미분 기능이 있음 . 

# 자동미분(Autograd) : 매 계산 과정마다 계산 과정의 미분값을 저장하고 있는 것.
# 파이토치 required_grad = True 로 설정하면 계산그래프 형태로 기록 ( 동영상 녹화와 비슷한 원리 )
# .backword() 호출하면 이 과정을 거꾸로 되감으면서 각 단계의 미분값을 계산 해 최종 기울기를 얻는다.





In [51]:
x = torch.ones(2,2, requires_grad=True)
x , x.size() # 배열보기

(tensor([[1., 1.],
         [1., 1.]], requires_grad=True),
 torch.Size([2, 2]))

In [52]:
y = x + 2 # y 도 계산 그래프에 추가
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [53]:
y.grad_fn

In [54]:
z = y * y * 3
out = z.mean()
z , out

(tensor([[27., 27.],
         [27., 27.]], grad_fn=<MulBackward0>),
 tensor(27., grad_fn=<MeanBackward0>))

In [55]:
# 기울기를 구하는 과정을 '역전파' 라고 함 --> 기울기 계산  //  backword() 를 사용하면 됌

# 최종결과가 out에서부터 시작해서 계산 그래프를 가꾸로 거슬러 오라가면서 미분의 연쇄법칙을 사용하여 미분값을 계산.
# out을 x에 대해서 미분

out.backward()
x.grad
# 최종 기울기는 x가 가지고 있음

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [56]:
# out = 1/4*(z1 + z2 + z3 + z4)
# z = 3y^2
# y = x + 2

#d-out / dxi = 

In [67]:
# 기울기 제어
# 역전파 , torch.no_grad , detach
# required_grad = True 연산 추척
import torch
x = torch.randn(3, requires_grad=True)
print(x)

# y 는 x 로부터 연산기록을 물려받음
y = x * 2
y.data  # 순수한 데이터에만 접근함.
# 노름 (유클리드 노름)  벡터의 크기를 측정하는 방법(원점으로부터 벡터까지의 거리)  모든 요소를 각각 제곱하고 모두 더해서 결과에 제곱근(루트)
# y의 실제 데이터의 크기를 확인해서 반복
i = 0
while y.data.norm()  < 1000:
    y = y*2
    i += 1
print(f'y : {y}')
print(f'반복횟수 : {i}  y = x*2^i+1')

# 벡터에 대한 역전파 (야코비안 행열)
# 벡터를 벡터로 미분하면 결과는 행열인 야코비안 행열
# pytorch 는 전체 야코비안 행열을 직접 계산하는 대신 야코비안 - 벡터 곱을 계산해서 메모리를 절약
v = torch.tensor( [0.1,1.0,0.0001],dtype=torch.float )
y.backward(v)  # y를 x에 대해 미분한 야코비안 행열과 입력으로 제공된 벡터 v를 곱하라는 의미

print(f'x.grad : {x.grad}')




tensor([ 1.0987, -1.2551, -0.3874], requires_grad=True)
y : tensor([ 1125.1118, -1285.2572,  -396.7133], grad_fn=<MulBackward0>)
반복횟수 : 9  y = x*2^i+1
x.grad : tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


'''
1. 스칼라 백워드 Scalar Backward : 역전파로 구하는 기울기가 하나일때
    out.backward()
    최종점수가 숫자 1개  ex)  수학공부 1시간 했을때 최종점수에 몇점의 영향을 줬는지 (미분)
    최종 목표가 하나(스칼라) 이기 때문에 각 원인(각 변수)의 기여도를 바로 계산

2. 벡터 백워드 Vector Backward : 기울기가 여러개일때
    y.vackward(v)
    과목별(국영수) 점수가 담긴 성적표(벡터)  ex) 공부시간이 성적에 얼마나 영향을 줬는지 물어보면 애매, 국어성적인지 영어성적인지.
    가중치 또는 중요도를 알려주는 벡터가 필요하다~  v = torch.tensor( [0.1,1.0,0.0001],dtype=torch.float )
    중요도를 반영해서 최종적으로 공부시간의 기여도를 확인한다는 것.
'''

In [ ]:
# 각 학습을 진행하면서 도중에 모델의 성능을 평가할 필요성이 있음 - 기울기 계산을 하면 안됨
with torch.no_grad():
    print(f'no_grad 내부 : {(x**2).requires_grad}')


# .derach()  계산그래프에서 tensor를 분리
print(f'detach 전 {y.requires_grad}')
y = x.detach()
print(f'detach 후 {y.requires_grad}')




no_grad 내부 : False
